id: pyews_test
version: -1
name: pyEWS_Test
description: ""
fromversion: "3.5.0"
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 1a3d18e6-6c3e-4f7b-8933-f8e929e6a37c
    type: start
    task:
      id: 1a3d18e6-6c3e-4f7b-8933-f8e929e6a37c
      version: -1
      description: ""
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: 606281da-a6f6-43d9-83e3-8f56f2313d02
    type: regular
    task:
      id: 606281da-a6f6-43d9-83e3-8f56f2313d02
      version: -1
      description: ""
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
      - "6"
      - "13"
      - "4"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 195
        }
      }
  "2":
    id: "2"
    taskid: c86c5d14-3783-418b-814b-4a5271768cfb
    type: regular
    task:
      id: c86c5d14-3783-418b-814b-4a5271768cfb
      version: -1
      description: ""
      name: Get searchable mailboxes
      script: EWS v2|||ews-get-searchable-mailboxes
      type: regular
      iscommand: true
      brand: EWS v2
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "3":
    id: "3"
    taskid: 33e1a432-f453-466e-8ac7-a2c956ee68d8
    type: regular
    task:
      id: 33e1a432-f453-466e-8ac7-a2c956ee68d8
      version: -1
      description: ""
      name: Verify Mailboxes context key
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      expectedValue: {}
      fields:
        simple: mailbox,mailboxId
      path:
        simple: EWS.Mailboxes
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "4":
    id: "4"
    taskid: 095a271e-6768-406a-8230-09a11d36a9e9
    type: regular
    task:
      id: 095a271e-6768-406a-8230-09a11d36a9e9
      version: -1
      description: ""
      name: Search mailboxes
      script: EWS v2|||ews-search-mailboxes
      type: regular
      iscommand: true
      brand: EWS v2
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      filter:
        simple: test
      mailbox-search-scope: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
  "5":
    id: "5"
    taskid: b6d4f244-a741-413b-871a-a5864a555722
    type: regular
    task:
      id: b6d4f244-a741-413b-871a-a5864a555722
      version: -1
      description: ""
      name: Verify Items context key
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
      - "10"
    scriptarguments:
      expectedValue: {}
      fields:
        simple: mailbox,subject,sender,hasAttachments,datetimeSent,datetimeReceived
      path:
        simple: EWS.Items.[0]
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
  "6":
    id: "6"
    taskid: 11bfb829-bf97-42de-88ed-ce993c4a8296
    type: regular
    task:
      id: 11bfb829-bf97-42de-88ed-ce993c4a8296
      version: -1
      description: ""
      name: Get contacts
      script: EWS v2|||ews-get-contacts
      type: regular
      iscommand: true
      brand: EWS v2
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      limit:
        simple: "1"
      target-mailbox:
        simple: demistoadmin@demisto.int
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
  "7":
    id: "7"
    taskid: 14cff168-51f8-4d99-82d6-2dcb4e87b55e
    type: regular
    task:
      id: 14cff168-51f8-4d99-82d6-2dcb4e87b55e
      version: -1
      description: ""
      name: Verify Contacts context key
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      expectedValue: {}
      fields:
        simple: phoneNumbers,displayName,emailAddresses
      path:
        simple: Account.Email.EwsContacts
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 545
        }
      }
  "8":
    id: "8"
    taskid: 0e5e77a3-be4a-496f-806a-4f105bd2c12d
    type: regular
    task:
      id: 0e5e77a3-be4a-496f-806a-4f105bd2c12d
      version: -1
      description: ""
      name: Get item attachment
      script: EWS v2|||ews-get-attachment
      type: regular
      iscommand: true
      brand: EWS v2
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      attachment-ids: {}
      item-id:
        simple: AAMkAGYxOTg3OTMzLTQ0MDYtNDg1Zi1hNDAzLTdhZjAyMGNhNDg4NABGAAAAAAB6Flhhw5PxTotLZ/er42qYBwDYq1Uc13t9Qa7AeRVeYnG3AAAAAAENAADYq1Uc13t9Qa7AeRVeYnG3AAAAAAkQAAA=
      target-mailbox: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
  "9":
    id: "9"
    taskid: 3c3d9a8d-e8c1-4fc3-8800-ee67ebda5863
    type: regular
    task:
      id: 3c3d9a8d-e8c1-4fc3-8800-ee67ebda5863
      version: -1
      description: ""
      name: Verify Items context
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      expectedValue: {}
      fields:
        simple: datetimeCreated,headers,subject,body,hasAttachments
      path:
        simple: EWS.Items.ItemAttachments
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
  "10":
    id: "10"
    taskid: 4d3d92e3-4506-4c6b-8558-5efe203f30a5
    type: regular
    task:
      id: 4d3d92e3-4506-4c6b-8558-5efe203f30a5
      version: -1
      description: ""
      name: Get file attachment
      script: EWS v2|||ews-get-attachment
      type: regular
      iscommand: true
      brand: EWS v2
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      attachment-ids:
        simple: AAMkAGYxOTg3OTMzLTQ0MDYtNDg1Zi1hNDAzLTdhZjAyMGNhNDg4NABGAAAAAAB6Flhhw5PxTotLZ/er42qYBwDYq1Uc13t9Qa7AeRVeYnG3AAAAAAENAADYq1Uc13t9Qa7AeRVeYnG3AACds5ROAAABEgAQAIyyWHXCJ8BLlkZfdtd6xS4=,AAMkAGYxOTg3OTMzLTQ0MDYtNDg1Zi1hNDAzLTdhZjAyMGNhNDg4NABGAAAAAAB6Flhhw5PxTotLZ/er42qYBwDYq1Uc13t9Qa7AeRVeYnG3AAAAAAENAADYq1Uc13t9Qa7AeRVeYnG3AACds5ROAAABEgAQAIyyWHXCJ8BLlkZfdtd6xS4=
      item-id:
        simple: AAMkAGYxOTg3OTMzLTQ0MDYtNDg1Zi1hNDAzLTdhZjAyMGNhNDg4NABGAAAAAAB6Flhhw5PxTotLZ/er42qYBwDYq1Uc13t9Qa7AeRVeYnG3AAAAAAENAADYq1Uc13t9Qa7AeRVeYnG3AACds5ROAAA=
      target-mailbox: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 720
        }
      }
  "11":
    id: "11"
    taskid: 0f33ed47-5d87-4260-8713-2791acf1e83a
    type: regular
    task:
      id: 0f33ed47-5d87-4260-8713-2791acf1e83a
      version: -1
      description: ""
      name: Verify EWS file attachment
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      expectedValue: {}
      fields:
        simple: attachmentId,attachmentName
      path:
        simple: EWS.Items.FileAttachments
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 895
        }
      }
  "12":
    id: "12"
    taskid: 6e2e77e0-ac4e-46cb-82ec-370bbd812a0a
    type: regular
    task:
      id: 6e2e77e0-ac4e-46cb-82ec-370bbd812a0a
      version: -1
      description: ""
      name: Verify file context
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      expectedValue: {}
      fields:
        simple: Name
      path:
        simple: File
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1070
        }
      }
  "13":
    id: "13"
    taskid: 633dca6c-72d4-4108-856b-3c982ff3bcdc
    type: regular
    task:
      id: 633dca6c-72d4-4108-856b-3c982ff3bcdc
      version: -1
      description: ""
      name: Get out of office status
      script: EWS v2|||ews-get-out-of-office
      type: regular
      iscommand: true
      brand: EWS v2
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      target-mailbox:
        simple: aleeng@demisto.int
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 370
        }
      }
  "14":
    id: "14"
    taskid: 401a68c7-9bd4-4286-8971-e750bff100c0
    type: regular
    task:
      id: 401a68c7-9bd4-4286-8971-e750bff100c0
      version: -1
      description: ""
      name: Verify out of office context key
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      expectedValue: {}
      fields:
        simple: state,start,end,mailbox
      path:
        simple: Account.Email.OutOfOffice
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 545
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1115,
        "width": 1670,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
