id: JoeSecurityTestPlaybook
version: 14
name: JoeSecurityTestPlaybook
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: b1516e55-8f73-4e59-8b09-1670bca3d8b4
    type: start
    task:
      id: b1516e55-8f73-4e59-8b09-1670bca3d8b4
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
      - "11"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: aec325de-81aa-4f4d-87ba-4342a6d18346
    type: regular
    task:
      id: aec325de-81aa-4f4d-87ba-4342a6d18346
      version: -1
      name: Start fresh
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "2":
    id: "2"
    taskid: 8d481524-ce50-4a35-88e3-2d4a1398bf5c
    type: regular
    task:
      id: 8d481524-ce50-4a35-88e3-2d4a1398bf5c
      version: -1
      name: Validate instance is working
      script: Joe Security|||joe-is-online
      type: regular
      iscommand: true
      brand: Joe Security
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "3":
    id: "3"
    taskid: 835cb787-f5a6-42dd-8869-54e517cab277
    type: regular
    task:
      id: 835cb787-f5a6-42dd-8869-54e517cab277
      version: -1
      name: Analyse a file using a url with out waiting
      script: Joe Security|||joe-analysis-submit-sample
      type: regular
      iscommand: true
      brand: Joe Security
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      comments: {}
      file_id: {}
      sample_url:
        simple: http://www.tutorialspoint.com/java/java_tutorial.pdf
      should_wait: {}
      systems: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "4":
    id: "4"
    taskid: e036e43b-eacc-4101-89d2-fbb089c566fa
    type: regular
    task:
      id: e036e43b-eacc-4101-89d2-fbb089c566fa
      version: -1
      name: Analyse a url without waiting
      script: Joe Security|||joe-analysis-submit-url
      type: regular
      iscommand: true
      brand: Joe Security
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      comments: {}
      should_wait:
        simple: "False"
      systems: {}
      url:
        simple: www.google.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "5":
    id: "5"
    taskid: fabb6446-0c9e-4c87-8d07-40dac22d0421
    type: regular
    task:
      id: fabb6446-0c9e-4c87-8d07-40dac22d0421
      version: -1
      name: Get info on the file analysis
      script: Joe Security|||joe-analysis-info
      type: regular
      iscommand: true
      brand: Joe Security
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      webid:
        simple: ${Joe.Analysis.[0].WebID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "6":
    id: "6"
    taskid: 86021972-f4bf-4d31-8820-17ead0b6d3c3
    type: regular
    task:
      id: 86021972-f4bf-4d31-8820-17ead0b6d3c3
      version: -1
      name: Get info on the URL analysis
      script: Joe Security|||joe-analysis-info
      type: regular
      iscommand: true
      brand: Joe Security
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      webid:
        simple: ${Joe.Analysis.[1].WebID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
  "7":
    id: "7"
    taskid: 1e5447da-152d-4f60-853f-eda3d6cd218a
    type: regular
    task:
      id: 1e5447da-152d-4f60-853f-eda3d6cd218a
      version: -1
      name: Analyse url with polling
      script: Joe Security|||joe-analysis-submit-url
      type: regular
      iscommand: true
      brand: Joe Security
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      comments: {}
      should_wait:
        simple: "True"
      systems: {}
      url:
        simple: http://www.tutorialspoint.com/java/java_tutorial.pdf
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
  "8":
    id: "8"
    taskid: b08554d5-83cc-4015-8f01-22c742f7afb7
    type: regular
    task:
      id: b08554d5-83cc-4015-8f01-22c742f7afb7
      version: -1
      name: List all analysis
      script: Joe Security|||joe-list-analysis
      type: regular
      iscommand: true
      brand: Joe Security
    nexttasks:
      '#none#':
      - "9"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
  "9":
    id: "9"
    taskid: b86abc4e-1b9c-4e81-883a-25167f21fb5d
    type: regular
    task:
      id: b86abc4e-1b9c-4e81-883a-25167f21fb5d
      version: -1
      name: Create sample file
      scriptName: FileCreateAndUpload
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      data:
        simple: qwerty
      entryId: {}
      filename:
        simple: zaq
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
  "10":
    id: "10"
    taskid: a9c434d1-ead2-482f-83eb-e406b779336b
    type: regular
    task:
      id: a9c434d1-ead2-482f-83eb-e406b779336b
      version: -1
      name: Run sample with file
      script: Joe Security|||joe-analysis-submit-sample
      type: regular
      iscommand: true
      brand: Joe Security
    scriptarguments:
      comments: {}
      file_id:
        simple: ${File.EntryID}
      sample_url: {}
      should_wait: {}
      systems: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1770
        }
      }
  "11":
    id: "11"
    taskid: a6dc7191-839a-4d11-8646-5f7e2e0a9336
    type: regular
    task:
      id: a6dc7191-839a-4d11-8646-5f7e2e0a9336
      version: -1
      name: Search command
      script: Joe Security|||joe-search
      type: regular
      iscommand: true
      brand: Joe Security
    nexttasks:
      '#none#':
      - "12"
      - "13"
      - "14"
      - "15"
    scriptarguments:
      query:
        simple: java_tutorial
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 195
        }
      }
  "12":
    id: "12"
    taskid: 5b40277a-1bcc-48d8-8c75-127843969178
    type: regular
    task:
      id: 5b40277a-1bcc-48d8-8c75-127843969178
      version: -1
      name: Download sample file
      script: Joe Security|||joe-download-sample
      type: regular
      iscommand: true
      brand: Joe Security
    scriptarguments:
      webid:
        simple: "513622"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
  "13":
    id: "13"
    taskid: 5cdcae14-81de-4de1-875d-de716ef3a260
    type: regular
    task:
      id: 5cdcae14-81de-4de1-875d-de716ef3a260
      version: -1
      name: Download fie Report - HTML
      script: Joe Security|||joe-download-report
      type: regular
      iscommand: true
      brand: Joe Security
    scriptarguments:
      type:
        simple: html
      webid:
        simple: "513622"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
  "14":
    id: "14"
    taskid: 6f863b3b-d5db-4d0c-8fe4-96fe723c69ee
    type: regular
    task:
      id: 6f863b3b-d5db-4d0c-8fe4-96fe723c69ee
      version: -1
      name: Download url Report - PDF
      script: Joe Security|||joe-download-report
      type: regular
      iscommand: true
      brand: Joe Security
    scriptarguments:
      type:
        simple: pdf
      webid:
        simple: "513696"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 370
        }
      }
  "15":
    id: "15"
    taskid: cfa334ee-c4e7-4617-8dfb-231313687b35
    type: regular
    task:
      id: cfa334ee-c4e7-4617-8dfb-231313687b35
      version: -1
      name: Download url Report -JSON
      script: Joe Security|||joe-download-report
      type: regular
      iscommand: true
      brand: Joe Security
    scriptarguments:
      type:
        simple: json
      webid:
        simple: "513696"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 370
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1815,
        "width": 2100,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
