id: test_arcsight_update_severity
version: -1
name: Test ArcSight update severity
description: Test the severity in the update case command in arcsight
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 06bb257b-801c-4f8c-8b83-843bc8f296cc
    type: start
    task:
      id: 06bb257b-801c-4f8c-8b83-843bc8f296cc
      version: -1
      name: ""
      description: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 549,
          "y": 46
        }
      }
  "1":
    id: "1"
    taskid: 5ff6cc2d-e0d9-4d4e-8dbf-852f1e053d0d
    type: regular
    task:
      id: 5ff6cc2d-e0d9-4d4e-8dbf-852f1e053d0d
      version: -1
      name: Delete Context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 549,
          "y": 226
        }
      }
  "2":
    id: "2"
    taskid: 6e9c70bd-8353-405b-804c-e3c919387007
    type: regular
    task:
      id: 6e9c70bd-8353-405b-804c-e3c919387007
      version: -1
      name: Get case
      description: Get a specific case from ESM
      script: ArcSight ESM_copy|||as-get-case
      type: regular
      iscommand: true
      brand: ArcSight ESM_copy
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      resourceId:
        simple: 7Kw-4m18BABC-AU7geXmpLw==
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 549,
          "y": 654
        }
      }
  "3":
    id: "3"
    taskid: 37679c1a-fb73-47be-8678-cbae928c6fa0
    type: regular
    task:
      id: 37679c1a-fb73-47be-8678-cbae928c6fa0
      version: -1
      name: Update case severity
      description: Updates a case
      script: ArcSight ESM_copy|||as-update-case
      type: regular
      iscommand: true
      brand: ArcSight ESM_copy
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      caseId:
        simple: 7Kw-4m18BABC-AU7geXmpLw==
      severity:
        simple: MARGINAL
      stage: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 549,
          "y": 445
        }
      }
  "4":
    id: "4"
    taskid: 40a656f9-2ae3-44ed-8ccb-810ce684415f
    type: regular
    task:
      id: 40a656f9-2ae3-44ed-8ccb-810ce684415f
      version: -1
      name: Verify Context
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      expectedValue:
        simple: MARGINAL
      fields: {}
      path:
        simple: ArcSightESM.Cases.consequenceSeverity
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 549,
          "y": 833
        }
      }
  "5":
    id: "5"
    taskid: 1c1bcf29-0c1b-47f7-8444-d01089be37e9
    type: regular
    task:
      id: 1c1bcf29-0c1b-47f7-8444-d01089be37e9
      version: -1
      name: Update case severity
      description: Updates a case
      script: ArcSight ESM_copy|||as-update-case
      type: regular
      iscommand: true
      brand: ArcSight ESM_copy
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      caseId:
        simple: 7Kw-4m18BABC-AU7geXmpLw==
      severity:
        simple: NONE
      stage: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 549,
          "y": 1036
        }
      }
  "6":
    id: "6"
    taskid: 50ed222a-e65f-4588-83a3-9f1871836e20
    type: regular
    task:
      id: 50ed222a-e65f-4588-83a3-9f1871836e20
      version: -1
      name: Verify Context
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      expectedValue:
        simple: NONE
      fields: {}
      path:
        simple: ArcSightESM.Cases.consequenceSeverity
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 549,
          "y": 1249
        }
      }
  "7":
    id: "7"
    taskid: 2297ec7b-e7cd-428a-8ebb-7940fec4181f
    type: title
    task:
      id: 2297ec7b-e7cd-428a-8ebb-7940fec4181f
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 549,
          "y": 1470
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1489,
        "width": 380,
        "x": 549,
        "y": 46
      }
    }
  }
inputs: []
outputs: []
releaseNotes: "-"
